### ISSUE TITLE
Its not working login redirect dashboard - following step b.

### ISSUE THREAD

**Issue by axilaris** [murshed/crowdfunding-login-form#1]
Hi,

I did these steps but its not working:

b.  
1. Upload the plugin files to the `/wp-content/plugins/plugin-name` directory, or install the plugin through the WordPress plugins screen directly.
2. Activate the plugin through the 'Plugins' screen in WordPress
3. Now check "Product" tab and click any Product "Quick Edit" button and change the Author.
4. Install and activate

How do you get login to redirect to dashboard ?
I noticed there are some code changes recently.

**Comment by murshed** [comment]
I am sorry @axilaris 

I have solved this issue and I have tested myself, it works fine.
